language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm  

before_script:
 - composer install
 - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  
matrix:
  allow_failures:
    - php: hhvm 
