													
	<footer class="footer">
		<div class="container">
			<div class="row footer-grids">
				<div class="terms contact">
					<h4><a href= "terms_conditions.php">Terms and Conditions </a></h4>
					<p>These Website Standard Terms and Conditions written on this 
					webpage shall manage your use of our website, 
					Nostalgic Eatery accessible at http://localhost/ict/index.php.
					</p>

				</div>
				<div class="terms contact">
					<h4>Contact No:</h4>
					<p> Nostalgic Eatery </p>
					<p> +919274747410 </p>
					<p><a href="contact.php"> Find Us Here </a> </p>
				</div>
				<div class="terms contact">
					<h4>Location:</h4>
					<p> 10 Chanakya complex, vania and circle, Nadiad Gujarat 387001, India </p>
				</div>
			</div>
		</div>
	</footer>
	<div class="copyright">
		<p class=""> © 2019 Nostalgic Eatery. All rights reserved | Design by ICTteam8</p>
	</div>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    
