													
	<footer class="footer">
		<div class="container">
			<div class="row footer-grids">
				<div class="terms contact">
					<h4>Terms and Conditions</h4>
					<p>you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
				</div>
				<div class="terms contact">
					<h4>Contact No:</h4>
					<p> +919274747410 </p>
				</div>
				<div class="terms contact">
					<h4>Location:</h4>
					<p> 10 Chanakya complex, vania and circle, Nadiad Gujarat 387001, India </p>
				</div>
			</div>
		</div>
	</footer>
	<div class="copyright">
		<p class=""> © 2019 Nostalgic Eatery. All rights reserved | Design by ICTteam8</p>
	</div>

    
