<div class="cusheader">
       		<div class="container-fluid">
				<div id="logo">
					<a href="index.php"> <img src="images/logo3.png"> </a>
				</div>
				<nav>
					<ul>
						<li > <a href = "index.php" id= "0" onClick= "nav_li_selected(0)"> Home </a> </li>
						<li> <a href = "services.php" id= "1" onClick= "nav_li_selected(1)"> Services </a> </li>
						<li> <a href = "feedback.php" id= "2" onClick= "nav_li_selected(2)">Feedback </a> </li>
						
						<li> <a href = "show_package.php" id= "3" onClick= "nav_li_selected(4)"> Package </a> </li>
						<li> <a href = "about.php" id= "4" onClick= "nav_li_selected(4)"> About Us </a> </li>
						<li > <a href = "contact.php" id= "5" onClick= "nav_li_selected(4)"> Contact Us</a> </li>
					</ul>
				</nav>
				<div class="button"> 
					<a href= "login.php" class="btn btn-two"> Sign In</a>
					<a href= "registration.php" class="btn btn-two">Sign Up</a>
				</div>
			</div>
		</div>