
	<!-- Navigation Bar -->
	        <nav>
			
			
			
			
	<div id="logo">
	<a href="index.php"> <img src="images/logo3.png" style="height:150px;"> </a>
	</div>
 
			
				<ul>
					<li > <a href = "index.php" id= "0" onClick= "nav_li_selected(0)"> Home </a> </li>
					<li> <a href = "services.php" id= "1" onClick= "nav_li_selected(1)"> Services </a> </li>
					<li> <a href = "feedback.php" id= "2" onClick= "nav_li_selected(2)">Feedback </a> </li>
					
					<li> <a href = "package.php" id= "3" onClick= "nav_li_selected(4)"> Package </a> </li>
					<li> <a href = "about.php" id= "4" onClick= "nav_li_selected(4)"> About Us </a> </li>
					<li > <a href = "contact.php" id= "5" onClick= "nav_li_selected(4)"> Contact Us</a> </li>
									</ul>
									
									<div class="button"> 
				<a href= "login.php" class="btn btn-two"> Admin/User Log In </a>
			
	</div>
			</nav>
	<!-- Navigation Bar ends -->
